# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SongodaCore

on:
  push:
    branches: [ master, development ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Workspace
        uses: ./.github/actions/prepare_workspace

      - name: Run tests
        run: 'mvn -B clean test'

  Build:
    runs-on: ubuntu-latest
    needs: [ Test ]
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Workspace
        uses: ./.github/actions/prepare_workspace

      # Build project
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload build artifacts
      - name: 'Upload Build Artifact: SongodaCore-*.jar'
        uses: actions/upload-artifact@v2
        with:
          name: SongodaCore-artifacts
          path: ./Core/target/SongodaCore-*.jar

  discord_webhook:
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - Test
      - Build
    if: ${{ always() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development') }}
    uses: ./.github/workflows/reusable_discord_build_status.yml
    secrets:
      webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
