# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build SongodaCore

on:
  push:
    branches: [ master, development ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout project files
      - uses: actions/checkout@v2

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          cache: maven

      # Build remapped Spigot versions
      - uses: SpraxDev/Action-SpigotMC@v4
        with:
          versions: 1.18.2, 1.19
          remapped: true

      # Build project
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload build artifacts
      - name: 'Upload Build Artifact: SongodaCore-*.jar'
        uses: actions/upload-artifact@v2
        with:
          name: SongodaCore-artifacts
          path: ./Core/target/SongodaCore-*.jar

  discord_webhook:
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build
    if: ${{ always() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development') }}
    continue-on-error: true
    uses: ./.github/workflows/reusable_discord_build_status.yml
      secrets:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
