name: Discord Build Status

on:
  workflow_call:
    secrets:
      webhook_url:
        required: true
        description: The Discord Webhook URL to send the message to.

permissions: read-all

jobs:
  Send:
    runs-on: ubuntu-latest
    steps:
      - uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.webhook_url }}

          username: OctoAgent
          avatar-url: https://github.githubassets.com/images/modules/logos_page/Octocat.png

          description: 'at `${{ github.ref }}`'
          include-details: true
